---
abstract: unknown
author:
  - 'Viktor Turskyi <koorchik@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-ValidateTiny
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 2.42
  Validate::Tiny: 0.08
  perl: 5.01
version: 0.12
